name: project_mad
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.17.6 <3.0.0'

dependencies: 
  carousel_slider: ^4.1.1
  cupertino_icons: ^1.0.2
  custom_navigation_bar: ^0.8.2
  dots_indicator: ^2.1.0
  firebase_core: ^2.3.0
  provider: ^6.0.4
  get: 4.6.5
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  assets: 
    - assets/gambar/logo_2.png
    - assets/gambar/logo_1.png
    - assets/gambar/Screenshot_4.png
    - assets/gambar/Screenshot_3.png
    - assets/gambar/Screenshot_2.png
    - assets/gambar/Screenshot_1.png
    - assets/gambar/minuman.png
  uses-material-design: true

